#!/usr/bin/env python3

"""
Se necesita entrar en https://exchange.blockchain.com , crear un usuario para logarse y una vez logado, generar la clave API, tal y como se especifica en: https://api.blockchain.com/v3/#/.

  To Get Started

  Create or log into your existing Blockchain.com Exchange account
  Select API from the drop down menu
  Fill out form and click “Create New API Key Now”
  Once generated you can view your keys under API Settings.
  Please be aware that the API key can only be used once it was verified via email.

  The API key must be set via the
    X-API-Token
  header.

  The base URL to be used for all calls is
  https://api.blockchain.com/v3/exchange

  Autogenerated clients for this API can be found here.

Ejemplo de llamada para obtener los datos:

  curl -H "X-API-Token: e3b35a91-ec09-40b1-a2ef-f09f66e1f8d7" -X GET "https://api.blockchain.com/v3/exchange/l3/BTC-USD"

"""

import sys
import pycurl
import io
import simplejson
import numpy as np
import pprint


class Blockchain:
	"""Clase maestra que 
	"""

	baseurl = "https://api.blockchain.com/v3/exchange"
	api_token = ""
	data = {}
	useragents = [
		"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36",
		"Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:33.0) Gecko/20100101 Firefox/33.0",
		"Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 7.1; Trident/5.0)",
		"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; InfoPath.2)",
		"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322)",
		"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; InfoPath.2)",
		"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0",
	]

	def __init__ (self, api_token):
		"""Inicializa la clase.

        :param api_token: API token
        :type api_token: str
		"""

		self.api_token = api_token


	def get_info (self, order):
		"""Obtiene los datos de compras (bids) y ventas (asks) con respecto a la relación entre la cryptomoneda y moneda real definidas (symbol).

        :param order: 
        :type order: str
        :return: Info
        :rtype: dict
		"""

		url = "%s/%s" % (self.baseurl, order)

		s = io.BytesIO()

		curl = pycurl.Curl()
		curl.setopt(pycurl.URL, url)
		curl.setopt(pycurl.USERAGENT, self.useragents[-1])
		curl.setopt(pycurl.HTTPHEADER, [ "X-API-Token: %s" % self.api_token ])
		curl.setopt(pycurl.FOLLOWLOCATION, True)
		curl.setopt(pycurl.WRITEFUNCTION, s.write)
		curl.setopt(pycurl.VERBOSE, 0)
		curl.perform()
		curl.close()

		self.data = simplejson.loads(s.getvalue())

		return self.data


class Blockchain_L3 (Blockchain):

	def get_info (self, cryptomoneda, monedareal):
		"""Obtiene los datos de compras (bids) y ventas (asks) con respecto a la relación entre la cryptomoneda y moneda real definidas (symbol).

        :param order: 
        :type order: str
        :param cryptomoneda: Cryptomoneda (BTC=bitcoin, ETH=Ethereum, ...)
        :type cryptomoneda: str
        :param monedareal: Moneda real (USD=dolar, GBP=libra esterlina, EUR=euro, ...)
        :type monedareal: str
        :return: Info
        :rtype: dict
		"""

		symbol = "%s-%s" % (cryptomoneda, monedareal)
		order = "l3/%s" % symbol

		return super().get_info(order)


	def get_stats (self, order_type):
		"""Obtiene las estadísticas de compras (bids) y ventas (asks):
        + Media de cantidad
        + Datos correspondientes a la mayor cantidad
        + Datos correspondientes a la menor cantidad
        + Precio total acumulado
        + Cantidad total acumulada

        :param order_type: "bids" (compras) o "asks" (ventas)
        :type order_type: str
        :return: Estadísticas de compras y ventas
        :rtype: dict
		"""

		average_qty = np.mean([ bid["qty"] for bid in self.data[order_type] ])
		max_qty = max(self.data[order_type], key=lambda x: x["qty"])
		min_qty = min(self.data[order_type], key=lambda x: x["qty"])
		total_qty = sum([ bid["qty"] for bid in self.data[order_type] ])
		total_px = sum([ bid["px"] for bid in self.data[order_type] ])

		r = {
			order_type: {
				"average_qty": average_qty,
				"greater_qty": max_qty,
				"lesser_qty": min_qty,
				"total_qty": total_qty,
				"total_px": total_px
			}
		}

		return r


if __name__ == "__main__":

	(api_token, ) = sys.argv[1:]

	bc = Blockchain_L3(api_token)
	bc.get_info("BTC", "USD")
	pp = pprint.PrettyPrinter(indent=4)
	pp.pprint(bc.get_stats("bids"))
	pp.pprint(bc.get_stats("asks"))


