# Generated by Django 4.0.3 on 2022-03-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidsAsks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=3, verbose_name='crypto')),
                ('realmoney', models.CharField(max_length=3, verbose_name='realmoney')),
                ('order', models.CharField(max_length=4, verbose_name='order')),
                ('px', models.FloatField(verbose_name='px')),
                ('qty', models.FloatField(max_length=80, unique=True, verbose_name='qty')),
                ('num', models.IntegerField(default=False, verbose_name='num')),
            ],
        ),
    ]
